### ISSUE TITLE
Adding discord blue theme

### ISSUE THREAD

**Issue by Mylan719** [0mniscient/BetterDiscord#14]
I got inspired recently and after browsing your selection of themes, which are mostly dark, I decided that I should create one light theme. There is next to no light theme fort discord. I took the original one and changed few things so that it was more to mi testes:
I have published it on my github here:
[github.com/Mylan719/Discord-light-theme](https://github.com/Mylan719/Discord-light-theme)

- It is my first theme for discord, there might be some things i overlooked 
- It is not complete override, it is complementary to the existing light theme.

If you would be so inclined, please add it to your page.

**Comment by 0mniscient** [comment]
Nice Theme! I have now added it to the website
