### ISSUE TITLE
Better Discord not loading resource 

### ISSUE THREAD

**Issue by Terunaa** [0mniscient/BetterDiscord#16]
A few days ago, I installed BD. It all went correctly and had no errors installing it. When I opened my DIscord back, I found this on the bottom right corner of Discord:
![capture](https://cloud.githubusercontent.com/assets/25496293/22535121/d3d414ba-e8c6-11e6-859e-9e5382c63ed6.PNG)
So I waited to see if it loaded, since it was my first time using BD, but nothing happened, even after hours of waiting. I can't access the BD settings in my User Settings since it's not there.
I tried reinstalling BD several times, then reinstalling Discord... but nothing worked.
My friends told me their BD worked normally in their computers, so maybe the issue has something to do with mine. Do you happen to have any idea what is causing this?

**Comment by 0mniscient** [comment]
Find support at https://discord.gg/0Tmfo5ZbORCRqbAd
